/*
 * Copyright (c) 2017 Lymia Alusyia <lymia@lymiahugs.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package moe.lymia.princess.lua

import scala.language.implicitConversions

/*

  Generated from the following code:
  ==================================

  def makeImplicit(count: Int) = {
    val n = (1 to count).toSeq

    val typeParameters = n.map(x => s"T$x : FromLua").mkString(", ")
    val fnTpParameters = n.map(x => s"T$x").mkString(", ")
    val passParameters = n.map(x => s"""implicitly[FromLua[T$x]].fromLua(L.L, L.L.value($x), "$x")""").mkString(", ")
    s"""
      |  // Functions for $count parameters
      |  implicit def nullFunction${count}2luaClosure[$typeParameters](fn: ($fnTpParameters) => Seq[LuaOutObject]): ScalaLuaClosure =
      |    ScalaLuaClosure(L => { fn($passParameters) })
      |  implicit def nullUnitFunction${count}2luaClosure[$typeParameters](fn: ($fnTpParameters) => Unit): ScalaLuaClosure =
      |    ScalaLuaClosure(L => { fn($passParameters); Seq() })
      |  implicit def function${count}2luaClosure[$typeParameters](fn: (LuaState, $fnTpParameters) => Seq[LuaOutObject]): ScalaLuaClosure =
      |    ScalaLuaClosure(L => { fn(L, $passParameters) })
      |  implicit def unitFunction${count}2luaClosure[$typeParameters](fn: (LuaState, $fnTpParameters) => Unit): ScalaLuaClosure =
      |    ScalaLuaClosure(L => { fn(L, $passParameters); Seq() })
    """.stripMargin.trim()
  }
  println(s"""
    |trait LuaGeneratedImplicits {
    |  ${(1 to 21).map(makeImplicit).mkString("\n\n  ")}
    |}
  """.stripMargin)

*/

trait LuaGeneratedImplicits {
  // Functions for 1 parameters
  implicit def nullFunction12luaClosure[T1 : FromLua](fn: (T1) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1")) })
  implicit def nullUnitFunction12luaClosure[T1 : FromLua](fn: (T1) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1")); Seq() })
  implicit def function12luaClosure[T1 : FromLua](fn: (LuaState, T1) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1")) })
  implicit def unitFunction12luaClosure[T1 : FromLua](fn: (LuaState, T1) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1")); Seq() })

  // Functions for 2 parameters
  implicit def nullFunction22luaClosure[T1 : FromLua, T2 : FromLua](fn: (T1, T2) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2")) })
  implicit def nullUnitFunction22luaClosure[T1 : FromLua, T2 : FromLua](fn: (T1, T2) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2")); Seq() })
  implicit def function22luaClosure[T1 : FromLua, T2 : FromLua](fn: (LuaState, T1, T2) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2")) })
  implicit def unitFunction22luaClosure[T1 : FromLua, T2 : FromLua](fn: (LuaState, T1, T2) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2")); Seq() })

  // Functions for 3 parameters
  implicit def nullFunction32luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua](fn: (T1, T2, T3) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3")) })
  implicit def nullUnitFunction32luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua](fn: (T1, T2, T3) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3")); Seq() })
  implicit def function32luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua](fn: (LuaState, T1, T2, T3) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3")) })
  implicit def unitFunction32luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua](fn: (LuaState, T1, T2, T3) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3")); Seq() })

  // Functions for 4 parameters
  implicit def nullFunction42luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua](fn: (T1, T2, T3, T4) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4")) })
  implicit def nullUnitFunction42luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua](fn: (T1, T2, T3, T4) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4")); Seq() })
  implicit def function42luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua](fn: (LuaState, T1, T2, T3, T4) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4")) })
  implicit def unitFunction42luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua](fn: (LuaState, T1, T2, T3, T4) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4")); Seq() })

  // Functions for 5 parameters
  implicit def nullFunction52luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua](fn: (T1, T2, T3, T4, T5) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5")) })
  implicit def nullUnitFunction52luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua](fn: (T1, T2, T3, T4, T5) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5")); Seq() })
  implicit def function52luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua](fn: (LuaState, T1, T2, T3, T4, T5) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5")) })
  implicit def unitFunction52luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua](fn: (LuaState, T1, T2, T3, T4, T5) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5")); Seq() })

  // Functions for 6 parameters
  implicit def nullFunction62luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua](fn: (T1, T2, T3, T4, T5, T6) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6")) })
  implicit def nullUnitFunction62luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua](fn: (T1, T2, T3, T4, T5, T6) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6")); Seq() })
  implicit def function62luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua](fn: (LuaState, T1, T2, T3, T4, T5, T6) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6")) })
  implicit def unitFunction62luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua](fn: (LuaState, T1, T2, T3, T4, T5, T6) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6")); Seq() })

  // Functions for 7 parameters
  implicit def nullFunction72luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua](fn: (T1, T2, T3, T4, T5, T6, T7) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7")) })
  implicit def nullUnitFunction72luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua](fn: (T1, T2, T3, T4, T5, T6, T7) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7")); Seq() })
  implicit def function72luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua](fn: (LuaState, T1, T2, T3, T4, T5, T6, T7) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7")) })
  implicit def unitFunction72luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua](fn: (LuaState, T1, T2, T3, T4, T5, T6, T7) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7")); Seq() })

  // Functions for 8 parameters
  implicit def nullFunction82luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua](fn: (T1, T2, T3, T4, T5, T6, T7, T8) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8")) })
  implicit def nullUnitFunction82luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua](fn: (T1, T2, T3, T4, T5, T6, T7, T8) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8")); Seq() })
  implicit def function82luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua](fn: (LuaState, T1, T2, T3, T4, T5, T6, T7, T8) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8")) })
  implicit def unitFunction82luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua](fn: (LuaState, T1, T2, T3, T4, T5, T6, T7, T8) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8")); Seq() })

  // Functions for 9 parameters
  implicit def nullFunction92luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua](fn: (T1, T2, T3, T4, T5, T6, T7, T8, T9) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9")) })
  implicit def nullUnitFunction92luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua](fn: (T1, T2, T3, T4, T5, T6, T7, T8, T9) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9")); Seq() })
  implicit def function92luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua](fn: (LuaState, T1, T2, T3, T4, T5, T6, T7, T8, T9) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9")) })
  implicit def unitFunction92luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua](fn: (LuaState, T1, T2, T3, T4, T5, T6, T7, T8, T9) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9")); Seq() })

  // Functions for 10 parameters
  implicit def nullFunction102luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua](fn: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10")) })
  implicit def nullUnitFunction102luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua](fn: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10")); Seq() })
  implicit def function102luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua](fn: (LuaState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10")) })
  implicit def unitFunction102luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua](fn: (LuaState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10")); Seq() })

  // Functions for 11 parameters
  implicit def nullFunction112luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua](fn: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11")) })
  implicit def nullUnitFunction112luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua](fn: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11")); Seq() })
  implicit def function112luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua](fn: (LuaState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11")) })
  implicit def unitFunction112luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua](fn: (LuaState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11")); Seq() })

  // Functions for 12 parameters
  implicit def nullFunction122luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua](fn: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12")) })
  implicit def nullUnitFunction122luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua](fn: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12")); Seq() })
  implicit def function122luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua](fn: (LuaState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12")) })
  implicit def unitFunction122luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua](fn: (LuaState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12")); Seq() })

  // Functions for 13 parameters
  implicit def nullFunction132luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua, T13 : FromLua](fn: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12"), implicitly[FromLua[T13]].fromLua(L.L, L.L.value(13), "13")) })
  implicit def nullUnitFunction132luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua, T13 : FromLua](fn: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12"), implicitly[FromLua[T13]].fromLua(L.L, L.L.value(13), "13")); Seq() })
  implicit def function132luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua, T13 : FromLua](fn: (LuaState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12"), implicitly[FromLua[T13]].fromLua(L.L, L.L.value(13), "13")) })
  implicit def unitFunction132luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua, T13 : FromLua](fn: (LuaState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12"), implicitly[FromLua[T13]].fromLua(L.L, L.L.value(13), "13")); Seq() })

  // Functions for 14 parameters
  implicit def nullFunction142luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua, T13 : FromLua, T14 : FromLua](fn: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12"), implicitly[FromLua[T13]].fromLua(L.L, L.L.value(13), "13"), implicitly[FromLua[T14]].fromLua(L.L, L.L.value(14), "14")) })
  implicit def nullUnitFunction142luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua, T13 : FromLua, T14 : FromLua](fn: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12"), implicitly[FromLua[T13]].fromLua(L.L, L.L.value(13), "13"), implicitly[FromLua[T14]].fromLua(L.L, L.L.value(14), "14")); Seq() })
  implicit def function142luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua, T13 : FromLua, T14 : FromLua](fn: (LuaState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12"), implicitly[FromLua[T13]].fromLua(L.L, L.L.value(13), "13"), implicitly[FromLua[T14]].fromLua(L.L, L.L.value(14), "14")) })
  implicit def unitFunction142luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua, T13 : FromLua, T14 : FromLua](fn: (LuaState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12"), implicitly[FromLua[T13]].fromLua(L.L, L.L.value(13), "13"), implicitly[FromLua[T14]].fromLua(L.L, L.L.value(14), "14")); Seq() })

  // Functions for 15 parameters
  implicit def nullFunction152luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua, T13 : FromLua, T14 : FromLua, T15 : FromLua](fn: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12"), implicitly[FromLua[T13]].fromLua(L.L, L.L.value(13), "13"), implicitly[FromLua[T14]].fromLua(L.L, L.L.value(14), "14"), implicitly[FromLua[T15]].fromLua(L.L, L.L.value(15), "15")) })
  implicit def nullUnitFunction152luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua, T13 : FromLua, T14 : FromLua, T15 : FromLua](fn: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12"), implicitly[FromLua[T13]].fromLua(L.L, L.L.value(13), "13"), implicitly[FromLua[T14]].fromLua(L.L, L.L.value(14), "14"), implicitly[FromLua[T15]].fromLua(L.L, L.L.value(15), "15")); Seq() })
  implicit def function152luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua, T13 : FromLua, T14 : FromLua, T15 : FromLua](fn: (LuaState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12"), implicitly[FromLua[T13]].fromLua(L.L, L.L.value(13), "13"), implicitly[FromLua[T14]].fromLua(L.L, L.L.value(14), "14"), implicitly[FromLua[T15]].fromLua(L.L, L.L.value(15), "15")) })
  implicit def unitFunction152luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua, T13 : FromLua, T14 : FromLua, T15 : FromLua](fn: (LuaState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12"), implicitly[FromLua[T13]].fromLua(L.L, L.L.value(13), "13"), implicitly[FromLua[T14]].fromLua(L.L, L.L.value(14), "14"), implicitly[FromLua[T15]].fromLua(L.L, L.L.value(15), "15")); Seq() })

  // Functions for 16 parameters
  implicit def nullFunction162luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua, T13 : FromLua, T14 : FromLua, T15 : FromLua, T16 : FromLua](fn: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12"), implicitly[FromLua[T13]].fromLua(L.L, L.L.value(13), "13"), implicitly[FromLua[T14]].fromLua(L.L, L.L.value(14), "14"), implicitly[FromLua[T15]].fromLua(L.L, L.L.value(15), "15"), implicitly[FromLua[T16]].fromLua(L.L, L.L.value(16), "16")) })
  implicit def nullUnitFunction162luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua, T13 : FromLua, T14 : FromLua, T15 : FromLua, T16 : FromLua](fn: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12"), implicitly[FromLua[T13]].fromLua(L.L, L.L.value(13), "13"), implicitly[FromLua[T14]].fromLua(L.L, L.L.value(14), "14"), implicitly[FromLua[T15]].fromLua(L.L, L.L.value(15), "15"), implicitly[FromLua[T16]].fromLua(L.L, L.L.value(16), "16")); Seq() })
  implicit def function162luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua, T13 : FromLua, T14 : FromLua, T15 : FromLua, T16 : FromLua](fn: (LuaState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12"), implicitly[FromLua[T13]].fromLua(L.L, L.L.value(13), "13"), implicitly[FromLua[T14]].fromLua(L.L, L.L.value(14), "14"), implicitly[FromLua[T15]].fromLua(L.L, L.L.value(15), "15"), implicitly[FromLua[T16]].fromLua(L.L, L.L.value(16), "16")) })
  implicit def unitFunction162luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua, T13 : FromLua, T14 : FromLua, T15 : FromLua, T16 : FromLua](fn: (LuaState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12"), implicitly[FromLua[T13]].fromLua(L.L, L.L.value(13), "13"), implicitly[FromLua[T14]].fromLua(L.L, L.L.value(14), "14"), implicitly[FromLua[T15]].fromLua(L.L, L.L.value(15), "15"), implicitly[FromLua[T16]].fromLua(L.L, L.L.value(16), "16")); Seq() })

  // Functions for 17 parameters
  implicit def nullFunction172luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua, T13 : FromLua, T14 : FromLua, T15 : FromLua, T16 : FromLua, T17 : FromLua](fn: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12"), implicitly[FromLua[T13]].fromLua(L.L, L.L.value(13), "13"), implicitly[FromLua[T14]].fromLua(L.L, L.L.value(14), "14"), implicitly[FromLua[T15]].fromLua(L.L, L.L.value(15), "15"), implicitly[FromLua[T16]].fromLua(L.L, L.L.value(16), "16"), implicitly[FromLua[T17]].fromLua(L.L, L.L.value(17), "17")) })
  implicit def nullUnitFunction172luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua, T13 : FromLua, T14 : FromLua, T15 : FromLua, T16 : FromLua, T17 : FromLua](fn: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12"), implicitly[FromLua[T13]].fromLua(L.L, L.L.value(13), "13"), implicitly[FromLua[T14]].fromLua(L.L, L.L.value(14), "14"), implicitly[FromLua[T15]].fromLua(L.L, L.L.value(15), "15"), implicitly[FromLua[T16]].fromLua(L.L, L.L.value(16), "16"), implicitly[FromLua[T17]].fromLua(L.L, L.L.value(17), "17")); Seq() })
  implicit def function172luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua, T13 : FromLua, T14 : FromLua, T15 : FromLua, T16 : FromLua, T17 : FromLua](fn: (LuaState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12"), implicitly[FromLua[T13]].fromLua(L.L, L.L.value(13), "13"), implicitly[FromLua[T14]].fromLua(L.L, L.L.value(14), "14"), implicitly[FromLua[T15]].fromLua(L.L, L.L.value(15), "15"), implicitly[FromLua[T16]].fromLua(L.L, L.L.value(16), "16"), implicitly[FromLua[T17]].fromLua(L.L, L.L.value(17), "17")) })
  implicit def unitFunction172luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua, T13 : FromLua, T14 : FromLua, T15 : FromLua, T16 : FromLua, T17 : FromLua](fn: (LuaState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12"), implicitly[FromLua[T13]].fromLua(L.L, L.L.value(13), "13"), implicitly[FromLua[T14]].fromLua(L.L, L.L.value(14), "14"), implicitly[FromLua[T15]].fromLua(L.L, L.L.value(15), "15"), implicitly[FromLua[T16]].fromLua(L.L, L.L.value(16), "16"), implicitly[FromLua[T17]].fromLua(L.L, L.L.value(17), "17")); Seq() })

  // Functions for 18 parameters
  implicit def nullFunction182luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua, T13 : FromLua, T14 : FromLua, T15 : FromLua, T16 : FromLua, T17 : FromLua, T18 : FromLua](fn: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12"), implicitly[FromLua[T13]].fromLua(L.L, L.L.value(13), "13"), implicitly[FromLua[T14]].fromLua(L.L, L.L.value(14), "14"), implicitly[FromLua[T15]].fromLua(L.L, L.L.value(15), "15"), implicitly[FromLua[T16]].fromLua(L.L, L.L.value(16), "16"), implicitly[FromLua[T17]].fromLua(L.L, L.L.value(17), "17"), implicitly[FromLua[T18]].fromLua(L.L, L.L.value(18), "18")) })
  implicit def nullUnitFunction182luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua, T13 : FromLua, T14 : FromLua, T15 : FromLua, T16 : FromLua, T17 : FromLua, T18 : FromLua](fn: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12"), implicitly[FromLua[T13]].fromLua(L.L, L.L.value(13), "13"), implicitly[FromLua[T14]].fromLua(L.L, L.L.value(14), "14"), implicitly[FromLua[T15]].fromLua(L.L, L.L.value(15), "15"), implicitly[FromLua[T16]].fromLua(L.L, L.L.value(16), "16"), implicitly[FromLua[T17]].fromLua(L.L, L.L.value(17), "17"), implicitly[FromLua[T18]].fromLua(L.L, L.L.value(18), "18")); Seq() })
  implicit def function182luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua, T13 : FromLua, T14 : FromLua, T15 : FromLua, T16 : FromLua, T17 : FromLua, T18 : FromLua](fn: (LuaState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12"), implicitly[FromLua[T13]].fromLua(L.L, L.L.value(13), "13"), implicitly[FromLua[T14]].fromLua(L.L, L.L.value(14), "14"), implicitly[FromLua[T15]].fromLua(L.L, L.L.value(15), "15"), implicitly[FromLua[T16]].fromLua(L.L, L.L.value(16), "16"), implicitly[FromLua[T17]].fromLua(L.L, L.L.value(17), "17"), implicitly[FromLua[T18]].fromLua(L.L, L.L.value(18), "18")) })
  implicit def unitFunction182luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua, T13 : FromLua, T14 : FromLua, T15 : FromLua, T16 : FromLua, T17 : FromLua, T18 : FromLua](fn: (LuaState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12"), implicitly[FromLua[T13]].fromLua(L.L, L.L.value(13), "13"), implicitly[FromLua[T14]].fromLua(L.L, L.L.value(14), "14"), implicitly[FromLua[T15]].fromLua(L.L, L.L.value(15), "15"), implicitly[FromLua[T16]].fromLua(L.L, L.L.value(16), "16"), implicitly[FromLua[T17]].fromLua(L.L, L.L.value(17), "17"), implicitly[FromLua[T18]].fromLua(L.L, L.L.value(18), "18")); Seq() })

  // Functions for 19 parameters
  implicit def nullFunction192luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua, T13 : FromLua, T14 : FromLua, T15 : FromLua, T16 : FromLua, T17 : FromLua, T18 : FromLua, T19 : FromLua](fn: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12"), implicitly[FromLua[T13]].fromLua(L.L, L.L.value(13), "13"), implicitly[FromLua[T14]].fromLua(L.L, L.L.value(14), "14"), implicitly[FromLua[T15]].fromLua(L.L, L.L.value(15), "15"), implicitly[FromLua[T16]].fromLua(L.L, L.L.value(16), "16"), implicitly[FromLua[T17]].fromLua(L.L, L.L.value(17), "17"), implicitly[FromLua[T18]].fromLua(L.L, L.L.value(18), "18"), implicitly[FromLua[T19]].fromLua(L.L, L.L.value(19), "19")) })
  implicit def nullUnitFunction192luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua, T13 : FromLua, T14 : FromLua, T15 : FromLua, T16 : FromLua, T17 : FromLua, T18 : FromLua, T19 : FromLua](fn: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12"), implicitly[FromLua[T13]].fromLua(L.L, L.L.value(13), "13"), implicitly[FromLua[T14]].fromLua(L.L, L.L.value(14), "14"), implicitly[FromLua[T15]].fromLua(L.L, L.L.value(15), "15"), implicitly[FromLua[T16]].fromLua(L.L, L.L.value(16), "16"), implicitly[FromLua[T17]].fromLua(L.L, L.L.value(17), "17"), implicitly[FromLua[T18]].fromLua(L.L, L.L.value(18), "18"), implicitly[FromLua[T19]].fromLua(L.L, L.L.value(19), "19")); Seq() })
  implicit def function192luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua, T13 : FromLua, T14 : FromLua, T15 : FromLua, T16 : FromLua, T17 : FromLua, T18 : FromLua, T19 : FromLua](fn: (LuaState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12"), implicitly[FromLua[T13]].fromLua(L.L, L.L.value(13), "13"), implicitly[FromLua[T14]].fromLua(L.L, L.L.value(14), "14"), implicitly[FromLua[T15]].fromLua(L.L, L.L.value(15), "15"), implicitly[FromLua[T16]].fromLua(L.L, L.L.value(16), "16"), implicitly[FromLua[T17]].fromLua(L.L, L.L.value(17), "17"), implicitly[FromLua[T18]].fromLua(L.L, L.L.value(18), "18"), implicitly[FromLua[T19]].fromLua(L.L, L.L.value(19), "19")) })
  implicit def unitFunction192luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua, T13 : FromLua, T14 : FromLua, T15 : FromLua, T16 : FromLua, T17 : FromLua, T18 : FromLua, T19 : FromLua](fn: (LuaState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12"), implicitly[FromLua[T13]].fromLua(L.L, L.L.value(13), "13"), implicitly[FromLua[T14]].fromLua(L.L, L.L.value(14), "14"), implicitly[FromLua[T15]].fromLua(L.L, L.L.value(15), "15"), implicitly[FromLua[T16]].fromLua(L.L, L.L.value(16), "16"), implicitly[FromLua[T17]].fromLua(L.L, L.L.value(17), "17"), implicitly[FromLua[T18]].fromLua(L.L, L.L.value(18), "18"), implicitly[FromLua[T19]].fromLua(L.L, L.L.value(19), "19")); Seq() })

  // Functions for 20 parameters
  implicit def nullFunction202luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua, T13 : FromLua, T14 : FromLua, T15 : FromLua, T16 : FromLua, T17 : FromLua, T18 : FromLua, T19 : FromLua, T20 : FromLua](fn: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12"), implicitly[FromLua[T13]].fromLua(L.L, L.L.value(13), "13"), implicitly[FromLua[T14]].fromLua(L.L, L.L.value(14), "14"), implicitly[FromLua[T15]].fromLua(L.L, L.L.value(15), "15"), implicitly[FromLua[T16]].fromLua(L.L, L.L.value(16), "16"), implicitly[FromLua[T17]].fromLua(L.L, L.L.value(17), "17"), implicitly[FromLua[T18]].fromLua(L.L, L.L.value(18), "18"), implicitly[FromLua[T19]].fromLua(L.L, L.L.value(19), "19"), implicitly[FromLua[T20]].fromLua(L.L, L.L.value(20), "20")) })
  implicit def nullUnitFunction202luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua, T13 : FromLua, T14 : FromLua, T15 : FromLua, T16 : FromLua, T17 : FromLua, T18 : FromLua, T19 : FromLua, T20 : FromLua](fn: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12"), implicitly[FromLua[T13]].fromLua(L.L, L.L.value(13), "13"), implicitly[FromLua[T14]].fromLua(L.L, L.L.value(14), "14"), implicitly[FromLua[T15]].fromLua(L.L, L.L.value(15), "15"), implicitly[FromLua[T16]].fromLua(L.L, L.L.value(16), "16"), implicitly[FromLua[T17]].fromLua(L.L, L.L.value(17), "17"), implicitly[FromLua[T18]].fromLua(L.L, L.L.value(18), "18"), implicitly[FromLua[T19]].fromLua(L.L, L.L.value(19), "19"), implicitly[FromLua[T20]].fromLua(L.L, L.L.value(20), "20")); Seq() })
  implicit def function202luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua, T13 : FromLua, T14 : FromLua, T15 : FromLua, T16 : FromLua, T17 : FromLua, T18 : FromLua, T19 : FromLua, T20 : FromLua](fn: (LuaState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12"), implicitly[FromLua[T13]].fromLua(L.L, L.L.value(13), "13"), implicitly[FromLua[T14]].fromLua(L.L, L.L.value(14), "14"), implicitly[FromLua[T15]].fromLua(L.L, L.L.value(15), "15"), implicitly[FromLua[T16]].fromLua(L.L, L.L.value(16), "16"), implicitly[FromLua[T17]].fromLua(L.L, L.L.value(17), "17"), implicitly[FromLua[T18]].fromLua(L.L, L.L.value(18), "18"), implicitly[FromLua[T19]].fromLua(L.L, L.L.value(19), "19"), implicitly[FromLua[T20]].fromLua(L.L, L.L.value(20), "20")) })
  implicit def unitFunction202luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua, T13 : FromLua, T14 : FromLua, T15 : FromLua, T16 : FromLua, T17 : FromLua, T18 : FromLua, T19 : FromLua, T20 : FromLua](fn: (LuaState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12"), implicitly[FromLua[T13]].fromLua(L.L, L.L.value(13), "13"), implicitly[FromLua[T14]].fromLua(L.L, L.L.value(14), "14"), implicitly[FromLua[T15]].fromLua(L.L, L.L.value(15), "15"), implicitly[FromLua[T16]].fromLua(L.L, L.L.value(16), "16"), implicitly[FromLua[T17]].fromLua(L.L, L.L.value(17), "17"), implicitly[FromLua[T18]].fromLua(L.L, L.L.value(18), "18"), implicitly[FromLua[T19]].fromLua(L.L, L.L.value(19), "19"), implicitly[FromLua[T20]].fromLua(L.L, L.L.value(20), "20")); Seq() })

  // Functions for 21 parameters
  implicit def nullFunction212luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua, T13 : FromLua, T14 : FromLua, T15 : FromLua, T16 : FromLua, T17 : FromLua, T18 : FromLua, T19 : FromLua, T20 : FromLua, T21 : FromLua](fn: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12"), implicitly[FromLua[T13]].fromLua(L.L, L.L.value(13), "13"), implicitly[FromLua[T14]].fromLua(L.L, L.L.value(14), "14"), implicitly[FromLua[T15]].fromLua(L.L, L.L.value(15), "15"), implicitly[FromLua[T16]].fromLua(L.L, L.L.value(16), "16"), implicitly[FromLua[T17]].fromLua(L.L, L.L.value(17), "17"), implicitly[FromLua[T18]].fromLua(L.L, L.L.value(18), "18"), implicitly[FromLua[T19]].fromLua(L.L, L.L.value(19), "19"), implicitly[FromLua[T20]].fromLua(L.L, L.L.value(20), "20"), implicitly[FromLua[T21]].fromLua(L.L, L.L.value(21), "21")) })
  implicit def nullUnitFunction212luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua, T13 : FromLua, T14 : FromLua, T15 : FromLua, T16 : FromLua, T17 : FromLua, T18 : FromLua, T19 : FromLua, T20 : FromLua, T21 : FromLua](fn: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12"), implicitly[FromLua[T13]].fromLua(L.L, L.L.value(13), "13"), implicitly[FromLua[T14]].fromLua(L.L, L.L.value(14), "14"), implicitly[FromLua[T15]].fromLua(L.L, L.L.value(15), "15"), implicitly[FromLua[T16]].fromLua(L.L, L.L.value(16), "16"), implicitly[FromLua[T17]].fromLua(L.L, L.L.value(17), "17"), implicitly[FromLua[T18]].fromLua(L.L, L.L.value(18), "18"), implicitly[FromLua[T19]].fromLua(L.L, L.L.value(19), "19"), implicitly[FromLua[T20]].fromLua(L.L, L.L.value(20), "20"), implicitly[FromLua[T21]].fromLua(L.L, L.L.value(21), "21")); Seq() })
  implicit def function212luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua, T13 : FromLua, T14 : FromLua, T15 : FromLua, T16 : FromLua, T17 : FromLua, T18 : FromLua, T19 : FromLua, T20 : FromLua, T21 : FromLua](fn: (LuaState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21) => Seq[LuaObject]): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12"), implicitly[FromLua[T13]].fromLua(L.L, L.L.value(13), "13"), implicitly[FromLua[T14]].fromLua(L.L, L.L.value(14), "14"), implicitly[FromLua[T15]].fromLua(L.L, L.L.value(15), "15"), implicitly[FromLua[T16]].fromLua(L.L, L.L.value(16), "16"), implicitly[FromLua[T17]].fromLua(L.L, L.L.value(17), "17"), implicitly[FromLua[T18]].fromLua(L.L, L.L.value(18), "18"), implicitly[FromLua[T19]].fromLua(L.L, L.L.value(19), "19"), implicitly[FromLua[T20]].fromLua(L.L, L.L.value(20), "20"), implicitly[FromLua[T21]].fromLua(L.L, L.L.value(21), "21")) })
  implicit def unitFunction212luaClosure[T1 : FromLua, T2 : FromLua, T3 : FromLua, T4 : FromLua, T5 : FromLua, T6 : FromLua, T7 : FromLua, T8 : FromLua, T9 : FromLua, T10 : FromLua, T11 : FromLua, T12 : FromLua, T13 : FromLua, T14 : FromLua, T15 : FromLua, T16 : FromLua, T17 : FromLua, T18 : FromLua, T19 : FromLua, T20 : FromLua, T21 : FromLua](fn: (LuaState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21) => Unit): ScalaLuaClosure =
    ScalaLuaClosure(L => { fn(L, implicitly[FromLua[T1]].fromLua(L.L, L.L.value(1), "1"), implicitly[FromLua[T2]].fromLua(L.L, L.L.value(2), "2"), implicitly[FromLua[T3]].fromLua(L.L, L.L.value(3), "3"), implicitly[FromLua[T4]].fromLua(L.L, L.L.value(4), "4"), implicitly[FromLua[T5]].fromLua(L.L, L.L.value(5), "5"), implicitly[FromLua[T6]].fromLua(L.L, L.L.value(6), "6"), implicitly[FromLua[T7]].fromLua(L.L, L.L.value(7), "7"), implicitly[FromLua[T8]].fromLua(L.L, L.L.value(8), "8"), implicitly[FromLua[T9]].fromLua(L.L, L.L.value(9), "9"), implicitly[FromLua[T10]].fromLua(L.L, L.L.value(10), "10"), implicitly[FromLua[T11]].fromLua(L.L, L.L.value(11), "11"), implicitly[FromLua[T12]].fromLua(L.L, L.L.value(12), "12"), implicitly[FromLua[T13]].fromLua(L.L, L.L.value(13), "13"), implicitly[FromLua[T14]].fromLua(L.L, L.L.value(14), "14"), implicitly[FromLua[T15]].fromLua(L.L, L.L.value(15), "15"), implicitly[FromLua[T16]].fromLua(L.L, L.L.value(16), "16"), implicitly[FromLua[T17]].fromLua(L.L, L.L.value(17), "17"), implicitly[FromLua[T18]].fromLua(L.L, L.L.value(18), "18"), implicitly[FromLua[T19]].fromLua(L.L, L.L.value(19), "19"), implicitly[FromLua[T20]].fromLua(L.L, L.L.value(20), "20"), implicitly[FromLua[T21]].fromLua(L.L, L.L.value(21), "21")); Seq() })
}
