name: Build distribution

on:
  push:
    branches: [ master ]
    tags: [ '*' ]

jobs:
  nativeBuildWin32:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: nightly
      - name: Compile for x86_64
        run: cargo build --release
        working-directory: modules/native/src/native
      - uses: actions/upload-artifact@v2
        with:
          name: princessedit_native.windows.x86_64.dll
          path: modules/native/src/native/target/release/princessedit_native.dll
  nativeBuildMacos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: nightly
          targets: aarch64-apple-darwin x86_64-apple-darwin
      - name: Compile for x86_64
        run: cargo build --release --target x86_64-apple-darwin
        working-directory: modules/native/src/native
      - uses: actions/upload-artifact@v2
        with:
          name: libprincessedit_native.macos.x86_64.dylib
          path: modules/native/src/native/target/release/libprincessedit_native.dylib
      - name: Compile for aarch64
        run: cargo build --release --target aarch64-apple-darwin
        working-directory: modules/native/src/native
      - uses: actions/upload-artifact@v2
        with:
          name: libprincessedit_native.macos.aarch64.dylib
          path: modules/native/src/native/target/release/libprincessedit_native.dylib
  nativeBuildLinux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: nightly
          targets: aarch64-unknown-linux-gnu x86_64-unknown-linux-gnu
      - name: Compile for x86_64
        run: cargo build --release --target x86_64-unknown-linux-gnu
        working-directory: modules/native/src/native
      - uses: actions/upload-artifact@v2
        with:
          name: libprincessedit_native.linux.x86_64.so
          path: modules/native/src/native/target/release/libprincessedit_native.so
      - name: Compile for aarch64
        run: cargo build --release --target aarch64-unknown-linux-gnu
        working-directory: modules/native/src/native
      - uses: actions/upload-artifact@v2
        with:
          name: libprincessedit_native.linux.aarch64.so
          path: modules/native/src/native/target/release/libprincessedit_native.so

  # Build for Linux
  buildOnLinux:
    runs-on: ubuntu-latest
    env:
      NATIVE_IMAGE_INSTALLED: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      # Setup environment
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 17
          graalvm-version: 22.0.0.2
          native-image: true
      - uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: nightly

      - name: Cache Ivy packages
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-dist
          path: ~/.ivy2

      # Build distribution package
      - name: Run sbt dist
        run: sbt -v clean dist
      - uses: actions/upload-artifact@v2
        with:
          name: linux-artifacts
          path: target/scala-2.13/dist/*
