name: Build distribution

on:
  push:
    branches: [ master ]
    tags: [ '*' ]

jobs:
  nativeBuilds:
    strategy:
      matrix:
        include:
          - platform: windows
            target: x86_64-pc-windows-msvc
            sourceName: princessedit_native.dll
            targetName: princessedit_native.windows.x86_64.dll
          - platform: macos
            target: x86_64-apple-darwin
            sourceName: libprincessedit_native.dylib
            targetName: libprincessedit_native.macos.x86_64.dylib
          - platform: macos
            target: aarch64-apple-darwin
            sourceName: libprincessedit_native.dylib
            targetName: libprincessedit_native.macos.aarch64.dylib
          - platform: linux
            target: x86_64-unknown-linux-gnu
            sourceName: libprincessedit_native.so
            targetName: libprincessedit_native.linux.x86_64.so
          - platform: linux
            target: aarch64-unknown-linux-gnu
            sourceName: libprincessedit_native.so
            targetName: libprincessedit_native.linux.aarch64.so
    runs-on: ${{ matrix.platform }}-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: nightly
          targets: ${{ matrix.target }}
      - name: Compile for ${{ matrix.target }}
        run: cargo build --release --target ${{ matrix.target }}
        working-directory: modules/native/src/native
      - run: mv ${{ matrix.sourceName }} ${{ matrix.targetName }}
        working-directory: modules/native/src/native/target/${{ matrix.target }}/release
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.targetName }}
          path: modules/native/src/native/target/${{ matrix.target }}/release/${{ matrix.targetName }}

  # Build for Linux
  buildOnLinux:
    runs-on: ubuntu-latest
    env:
      NATIVE_IMAGE_INSTALLED: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      # Setup environment
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 17
          graalvm-version: 22.0.0.2
          native-image: true
      - uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: nightly
      - name: Cache Ivy packages
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-dist
          path: ~/.ivy2

      # Build distribution package
      - name: Run sbt dist
        run: sbt -v clean dist
      - uses: actions/upload-artifact@v2
        with:
          name: linux-artifacts
          path: target/scala-2.13/dist/*

  buildUniversal:
    runs-on: ubuntu-latest
    needs:
      - nativeBuilds
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      # Setup environment
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: nightly
      - name: Cache Ivy packages
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-distUniversal
          path: ~/.ivy2

      # Build distribution package
      - uses: actions/download-artifact@v2
        with:
          name: princessedit_native.windows.x86_64.dll
          path: modules/native/target
      - uses: actions/download-artifact@v2
        with:
          name: libprincessedit_native.macos.x86_64.dylib
          path: modules/native/target
      - uses: actions/download-artifact@v2
        with:
          name: libprincessedit_native.macos.aarch64.dylib
          path: modules/native/target
      - uses: actions/download-artifact@v2
        with:
          name: libprincessedit_native.linux.x86_64.so
          path: modules/native/target
      - uses: actions/download-artifact@v2
        with:
          name: libprincessedit_native.linux.aarch64.so
          path: modules/native/target

      - name: Check modules/native/target contents
        run: ls -alh
        working-directory: modules/native/target
      - name: Run sbt dist
        run: sbt -v clean distUniversal

      - uses: actions/upload-artifact@v2
        with:
          name: universal-artifacts
          path: target/scala-2.13/dist/*